spring:
  application:
    name: user-service-api
  data:
    mongodb:
      uri: 'mongodb+srv://help-desk-user:help-desk-user@clusterhelpdesk.cuhqe.mongodb.net/helpdeskdb?retryWrites=true&w=majority&appName=ClusterHelpDesk'
      autoIndexCreation: true
spring-doc:
  openapi:
    title: "User Service API"
    description: "Component responsible for user management"
    version: "1.0.0"