spring:
  application:
    name: user-service-api
  data:
    mongodb:
      uri: 'mongodb+srv://help-desk-user:<db_password>@clusterhelpdesk.cuhqe.mongodb.net/helpdeskdb?retryWrites=true&w=majority&appName=ClusterHelpDesk'
      autoIndexCreation: true